<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	  <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
	  <PublishSingleFile>true</PublishSingleFile>
	  <VersionPrefix>1.0.0.60</VersionPrefix>
	  <Version>$(VersionPrefix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="powershell -Command &quot;$sourceContent = Get-Content 'C:\Users\OvsyannikovID\Desktop\AWSLinux\AWS\AWS\AWS.csproj'; $sourceVersion = ($sourceContent | Where-Object { $_ -match '&lt;VersionPrefix&gt;(.*)&lt;/VersionPrefix&gt;' } | ForEach-Object { $matches[1] } | Select-Object -First 1); if ($sourceVersion) { $targetContent = Get-Content 'C:\Users\OvsyannikovID\Desktop\AWSLinux\AWS\AWS.Desktop\AWS.Desktop.csproj'; $targetContent -replace '&lt;VersionPrefix&gt;.*&lt;/VersionPrefix&gt;', ('&lt;VersionPrefix&gt;' + $sourceVersion + '&lt;/VersionPrefix&gt;') | Set-Content 'C:\Users\OvsyannikovID\Desktop\AWSLinux\AWS\AWS.Desktop\AWS.Desktop.csproj' }&quot;" />
  </Target>
</Project>
